apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-td6s
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-td6s
    app.kubernetes.io/part-of: test-app-cbxt
  name: devfile-sample-python-basic-td6s
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-td6s
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-td6s
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-pttz-tenant/test-app-cbxt/devfile-sample-python-basic-td6s@sha256:f33022f944764af24d8f701ad67107f1a1f0ec33bd71c6d2918a1e075c8bd2c2
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
